### ISSUE TITLE
VideoDecode troubles with various videos

### ISSUE THREAD

**Issue by HEBOS** [jlennox/NvEncSharp#2]
Hi,

I was very excited when I found your project, especially due to lack of any solution which would help us read frames into GPU for further processing on Windows.
For example, there is no way to get OpenCV+FFMPEG, or any other way into NVIDIA GPU. Only CPU works resulting in reading rate being just to slow with any other solution (Gstreamer doesn't even have any NVIDIA plugins for Windows yet).
However, I'm not able to get your VideoDecode project sample to work.

If I try with 4K video, it raises an exception on line 159, where the following code can be found: "backbufferStream.Write(packet.Packet)".

The exception states:
"System.NotSupportedException: 'Memory stream is not expandable.'"

However, if I try with HD video (1920x1080), then the loop seems run (if I put a breakpoint, it will be hit), but the display window is frozen (gray), and no video is being displayed, so I'm not sure if it works.

4K video
https://drive.google.com/file/d/1MWniv_hCi-EXiQFflnt3PGJ7cdwJRGRd/view?usp=sharing

Command-line used:
--input c:\t\x.mp4

HD video
https://drive.google.com/file/d/1uFQIyKy-_vKFSyF4Fy0TdL7SE_hnXF4T/view?usp=sharing

Command-line used:
--input c:\t\x2.mp4

I would appreciate any help.

**Comment by jlennox** [comment]
@HEBOS Thanks for the interest in the project!

I really should of made it clearer in the project. The decoder example does not support file formats, it only supports raw h264 NAL data. You can use ffmpeg to convert your input file like this: `ffmpeg -i x.mp4 -c copy raw.h264`

Here's an image of it working on your 4k file after conversion:
![decode_example](https://user-images.githubusercontent.com/836194/89064587-1c45ba00-d31f-11ea-9182-6d2ed4c84bee.png)

I believe there's libraries that would make supporting this viable and I considered adding wrappings for them but I did not get around to that. Off the top of my head I do not remember the name but it's used by the official nVidia decoder code samples.

Also notice in my screen shot that the name/PCI address are messed up. Woops! I'll have a fix checked in for that later.

Let me know if there's anything else and we can reopen this issue or make a new one!
